AppContable/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'AppContable.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url('^admin/',admin.site.urls),
    url('', include('main.urls')),
]

main/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.main,name='main'),
    url(r'^newService/$', views.newService),
    url(r'^newCustomer/$', views.newCustomer,name='newCustomer'),
    url(r'^newTechnician/$', views.newTechnician),
    url(r'^newServi/$', views.newServi),

    url(r'^remissionHistory/$', views.remissionHistory),
    url(r'^customerHistory/$', views.customerHistory),    
    url(r'^techniciansHistory/$', views.techniciansHistory), 
    url(r'^configuration/$', views.configuration), 
    url(r'^customer/(?P<pk>[0-9]+)/$', views.customer_detail, name='customer_detail'),
    url(r'^technician/(?P<pk>[0-9]+)/$', views.technician_detail, name='technician_detail'),
    url(r'^remission/(?P<pk>[0-9]+)/$', views.remission_detail, name='remission_detail'),
    url(r'^servi/(?P<pk>[0-9]+)/$', views.servi_detail, name='servi_detail'),

    url(r'^SaveCustomer/$', views.SaveCustomer),
    url(r'^SaveTecnician/$', views.SaveTecnician),
    url(r'^SaveServi/$', views.SaveServi),
    url(r'^delete/$', views.delete),

    url(r'^customerList/$', views.customerList),
    url(r'^technicianList/$', views.technicianList),
    url(r'^servicesList/$', views.servicesList),

    

    ]

main/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Technicians(models.Model):
    IDD = models.AutoField(primary_key=True)
    id_person = models.CharField(max_length=200,unique=True)
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    address =  models.CharField(max_length=200,default=' ')

    def __str__(self):
        return self.name
    class Meta:
        ordering = ('name',)

class customers(models.Model):
    IDD = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    CCNIT = models.CharField(max_length=200,unique=True)
    Department = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    cell = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    ext = models.CharField(max_length=200,blank=True,default='0')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

class Services(models.Model):
    IDD = models.AutoField(primary_key=True)
    ID_service = models.CharField(max_length=200,unique=True)
    service = models.CharField(max_length=200)
    value = models.FloatField()

    def __str__(self):
        strr = self.ID_service+' '+self.service+' '+str(self.value)
        return strr

    class Meta:
        ordering = ('service',)    

class registeredServices(models.Model):
    IDD = models.AutoField(primary_key=True)
    remission = models.CharField(max_length=200,unique=True)
    billNum = models.CharField(max_length=200,blank=True,default=' ')
    dateBill = models.DateTimeField(blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    customer = models.ForeignKey(customers, on_delete=models.CASCADE)
    dateService = models.DateTimeField(default=timezone.now)
    technician = models.ForeignKey(Technicians, on_delete=models.CASCADE)
    service  = models.ManyToManyField(Services)
    Observation = models.CharField(max_length=200,default='Ninguna')
    stateRemission = models.IntegerField(blank=True,default=0)
    paidOut = models.FloatField(blank=True,default=0.0)
    residue = models.FloatField(blank=True,default=0.0)
    estateBill = models.IntegerField(blank=True,default=0)

    class Meta:
        ordering = ('remission',)


class SpecificServices(models.Model):
    IDD = models.AutoField(primary_key=True)
    remission = models.ForeignKey(registeredServices, on_delete=models.CASCADE)
    amount = models.IntegerField()
    service = models.ForeignKey(Services, on_delete=models.CASCADE)
    value = models.FloatField()
    total =models.FloatField()
    generalTotal = models.FloatField()
    IVA = models.FloatField()
    RETEIVA = models.FloatField()
    RETEICA = models.FloatField()
    RETEFUENTE = models.FloatField()
    generalTotalWithTax = models.FloatField()

    class Meta:
        ordering = ('remission',)

main/forms.py
from django import forms
from .models import *

class DateInput(forms.DateInput):
    input_type = 'date'


class customersForm(forms.ModelForm):
    class Meta:
        model = customers
        fields = ( 'CCNIT','name','Department','city','address','cell','phone','ext',)

class techniciansForm(forms.ModelForm):
    class Meta:
        model = Technicians
        fields = ( 'id_person','name','phone','address',)

class servicesForm(forms.ModelForm):
    class Meta:
        model = Services
        fields = ( 'ID_service','service','value',)

class newServiceForm(forms.ModelForm):
    class Meta:
        model = registeredServices
        fields = ( 'remission','date','customer','dateService','technician','service','Observation','stateRemission',)
        widgets = {
            'date': DateInput(),
            'dateService': DateInput(),
        }

main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .forms import *
from django.shortcuts import redirect
from django.contrib import messages
from main.models import *
from django.shortcuts import render, get_object_or_404
# Create your views here.

def main(request):
    return render(request, 'main/main.html', {})
def delete(request):
	if request.method == "GET":
		IDD = request.GET.get('IDD')
		tipo = request.GET.get('tipo')
		if tipo=='1':
			custo = get_object_or_404(Services, IDD=IDD)
		if tipo=='2':
			custo = get_object_or_404(customers, IDD=IDD)
		if tipo=='3':
			custo = get_object_or_404(Technicians, IDD=IDD)
		custo.delete()
		messages.success(request,'Información borrada')

def SaveServi(request):
	if request.method == "GET":
		IDD = request.GET.get('IDD')
		custo = get_object_or_404(Services, IDD=IDD)
		custo.ID_service = request.GET.get('ID_service')
		custo.service = request.GET.get('service')
		custo.value = float(request.GET.get('value').replace(',','.'))
		custo.save()
		messages.success(request,'Técnico actualizado')

	return render(request, 'main/main.html', {})

def SaveTecnician(request):
	if request.method == "GET":
		IDD = request.GET.get('IDD')
		custo = get_object_or_404(Technicians, IDD=IDD)
		custo.id_person = request.GET.get('id_person')
		custo.name = request.GET.get('name')
		custo.phone = request.GET.get('phone')
		custo.save()
		messages.success(request,'Servicio actualizado')

	return render(request, 'main/main.html', {})

def SaveCustomer(request):
	if request.method == "GET":
		IDD = request.GET.get('IDD')
		custo = get_object_or_404(customers, IDD=IDD)
		print(custo.name)
		custo.name = request.GET.get('name')
		custo.CCNIT = request.GET.get('CCNIT')
		custo.Department = request.GET.get('Department')
		custo.city = request.GET.get('city')
		custo.cell = request.GET.get('cell')
		custo.address = request.GET.get('address')
		custo.phone = request.GET.get('phone')
		custo.ext = request.GET.get('ext')
		custo.save()
		messages.success(request,'Cliente actualizado')

	return render(request, 'main/main.html', {})

def customerList(request):
	query = request.GET.get('q')
	if query:
		info = customers.objects.filter(name__icontains=query)
		return render(request, 'main/customerList.html', {'info':info})

	info = customers.objects.all()
	return render(request, 'main/customerList.html',{'info':info})

def technicianList(request):
	query = request.GET.get('q')
	if query:
		info = Technicians.objects.filter(name__icontains=query)
		return render(request, 'main/technicianList.html', {'info':info})

	info = Technicians.objects.all()
	return render(request, 'main/technicianList.html',{'info':info})

def servicesList(request):
	query = request.GET.get('q')
	if query:
		info = Services.objects.filter(ID_service__icontains=query)
		return render(request, 'main/servicesList.html', {'info':info})

	info = Services.objects.all()
	return render(request, 'main/servicesList.html',{'info':info})
	
def newServi(request):
	if request.method == "POST":
		form = servicesForm(request.POST)
		if form.is_valid():
			servi = form.save(commit=False)
			servi.save()
			messages.success(request,'Servicio almacenado')
			return render(request, 'main/main.html')
	else:
		form = servicesForm()
	return render(request, 'main/newServi.html', {'form': form})

def newService(request):
	servv = Services.objects.all()
	if request.method == "POST":
		form = newServiceForm(request.POST)
		if form.is_valid():
			customer = form.save()
			customer.save()
			messages.success(request,'Servicio almacenado')
			return render(request, 'main/main.html')
	else:
		form = newServiceForm()
	return render(request, 'main/newService.html', {'form': form,'servv':servv})

def newCustomer(request):
	if request.method == "POST":
		form = customersForm(request.POST)
		if form.is_valid():
			customer = form.save(commit=False)
			customer.save()
			messages.success(request,'Cliente almacenado')
			return render(request, 'main/main.html')
	else:
		form = customersForm()
	return render(request, 'main/newCustomer.html', {'form': form})


def newTechnician(request):
	if request.method == "POST":
		form = techniciansForm(request.POST)
		if form.is_valid():
			customer = form.save(commit=False)
			customer.save()
			messages.success(request,'Técnico almacenado')
			return render(request, 'main/main.html')
	else:
		form = techniciansForm()
	return render(request, 'main/newTechnician.html', {'form': form})


def remissionHistory(request):
	query = request.GET.get('q')
	
	if query:
		remision = registeredServices.objects.filter(remission__icontains=query).order_by('date')
		return render(request, 'main/remissionHistory.html', {'info':remision})
	remision = registeredServices.objects.all().order_by('date')
	return render(request, 'main/remissionHistory.html', {'info':remision})

def customerHistory(request):
	return render(request, 'main/customerHistory.html')

def techniciansHistory(request):
	return render(request, 'main/techniciansHistory.html')

def configuration(request):
	return render(request, 'main/configuration.html')

def customer_detail(request,pk):
    customer = get_object_or_404(customers, CCNIT=pk)
    return render(request, 'main/customer_detail.html', {'customer': customer})

def technician_detail(request,pk):
    technician = get_object_or_404(Technicians, id_person=pk)
    return render(request, 'main/technician_detail.html', {'technician': technician})

def remission_detail(request,pk):
    remission = get_object_or_404(registeredServices, remission=pk)
    services = remission.service.all()
    return render(request, 'main/remission_detail.html', {'remission' : remission , 'services' : services})

def servi_detail(request,pk):
    remission = get_object_or_404(Services, ID_service=pk)
    return render(request, 'main/servi_detail.html', {'remission' : remission})

main/templates/main/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>AppContable</title>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>  

        <!--  Scripts-->

    </head>

    <body>
        <header>
            <input type="checkbox" id="btn-menu">
            <label for="btn-menu">
                <img src="{% static 'image/img_menu.png' %}" alt="menu">
            </label>
            <nav class="menu">
                <ul>
                    <li><a href="/">Inicio</a></li>
                    <li><a href="/newCustomer">Nuevo cliente</a></li>
                    <li><a href="/newTechnician">Nuevo Técnico</a></li>
                    <li><a href="/newServi">Nuevo Sercicio</a></li>
                    <li><a href="/configuration">Configuraciones</a></li>

                </ul>
            </nav>
        </header>
        {% if messages %}
        <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
                </ul>
                {% endif %}
                {% block content %}
                {% endblock %}
                <script src="{% static 'js/jquery-3.3.1.js'%}"></script>
                <script src="{% static 'js/main.js'%}"></script>
            </body>

</html>

main/templates/main/customerHistory.html
{% extends 'main/base.html' %}
{% block content %}




<h2>Historial de clientes</h2>

{% endblock %}

main/templates/main/customer_detail.html
{% extends 'main/base.html' %}
{% block content %}

<h2>Detalle de cliente</h2>
{% if customer %}
    <div>
        <table>
            <form action="/SaveCustomer" method="get" id="saveForm">
                <td><input type="text" name="IDD" style="display: none;" value="{{customer.IDD}}"></td>           
            <tr>
                <th>Nombre: </th>
                <td><input type="text" name="name"  value="{{customer.name}}"></td>
            </tr>
            <tr>
                <th>Indentificación</th>
                <td><input type="text" name="CCNIT"  value="{{ customer.CCNIT }}"></td>
            </tr>
            <tr>
            <tr>
                <th>Departamento</th>
                <td><input type="text" name="Department"  value="{{customer.Department}}"></td>
            </tr>
            <tr>
                <th>Ciudad</th>
                <td><input type="text" name="city"  value="{{customer.city}}"></td>
            </tr>
            <tr>
                    <th>Dirección</th>
                    <td><input type="text" name="address"  value="{{customer.address}}"></td>
            </tr>
            <tr>
                <th>Celular</th>
                <td><input type="text" name="cell"  value="{{customer.cell}}"></td>
            </tr>
            <tr>
                <th>Télefono</th>
                <td><input type="text" name="phone"  value="{{customer.phone}}"></td>
            </tr>
            <tr>
                <th>Extención</th>
                <td><input type="text" name="ext"  value="{{customer.ext}}"><br>
                <button type="submit">Guardar</button> 
                </td>
            </tr>
           
        </form>  
        </table>  
    </div>
{% endif %}
{% endblock %}

main/templates/main/main.html
{% extends 'main/base.html' %}
{% block content %}

<div class="general">

    <div id="newService">
        <h2>Nuevo servicio</h2>
        <a href="/newService">Entrar</a>
    </div>
    <div id="remissionHistory">
        <h2>Historial de remisiones</h2>
        <a href="/remissionHistory">Entrar</a>
    </div>
    <div id="customerHistory">
        <h2>Historial de cliente</h2>
        <a href="/customerHistory">Entrar</a>
    </div>
    <div id="techniciansHistory">
        <h2>Historial de ténico</h2>
        <a href="/techniciansHistory">Entrar</a>
    </div>

</div>

{% endblock %}

main/templates/main/newCustomer.html
{% extends 'main/base.html' %}
{% block content %}
<h2>Nuevo cliente</h2>
<form method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>

{% endblock %}

main/templates/main/newServi.html
{% extends 'main/base.html' %}
{% block content %}

<h2>Nuevo servicio disponible</h2>
<form method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Guardar</button>
</form>
{% endblock %}

main/templates/main/newService.html
{% extends 'main/base.html' %}
{% block content %}

<h2>Ingresar nuevo Servicio</h2>
<form method="POST" class="post-form">{% csrf_token %}
        <p>
            {{ form.remission.errors }}
            <label for="{{ form.remission.id_for_label }}">Numero de remisión:</label> 
            {{ form.remission }}
        </p>

        <p>
            {{ form.date.errors }}
            <label for="{{ form.date.id_for_label }}">Fecha de emisión:</label>         
            {{ form.date}}
        </p>
        <p>
            {{ form.customer.errors }}
            <label for="{{ form.customer.id_for_label }}">Cliente:</label> 
            {{ form.customer }}
        </p>
        <p>
            {{ form.dateService.errors }}
            <label for="{{ form.dateService.id_for_label }}">Fecha de servicio:</label> 
             {{ form.dateService }}
        </p>
        <p>
              {{ form.technician.errors }}
              <label for="{{ form.technician.id_for_label }}">Técnico:</label> 
               {{ form.technician }}
        </p>
        <p>
            {{ form.Observation.errors }}
            <label for="{{ form.Observation.id_for_label }}">Observación:</label> 
            {{ form.Observation }}
        </p>
        <p>
            {{ form.stateRemission.errors }}
            <label for="{{ form.stateRemission.id_for_label }}">Estado de remisión:</label> 
            {{ form.stateRemission }}
        </p>
    <button type="submit" class="save btn btn-default">Guardar</button>
</form>




    {% if servv %}
            <label for="id_service">Servicios:</label> 
            <select multiple="multiple" id="id_service" name="service">
                {% for a in servv %}
                <option value="{{a.ID_service}} {{a.service}} {{a.value}}">{{a.service}} </option>
                {% endfor %}
            </select>
    {% endif %}
    <button id="add"> Agregar </button>
    <div id="items"></div>
{% endblock %}

main/templates/main/newTechnician.html
{% extends 'main/base.html' %}
{% block content %}

<h2>Nuevo técnico</h2>
<form method="POST" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Guardar</button>
</form>
{% endblock %}

main/templates/main/remissionHistory.html
{% extends 'main/base.html' %}
{% block content %}

<h2>Historial de remisiones</h2>

<div>
    <form action="/remissionHistory" method="get" id="searchform">
        <input name="q" type="text" placeholder="Buscar aquí..." value="{{query}}" required>
        <button type="submit">Buscar</button>
    </form>
</div>


{% if info %}


    <table>
            <tr>
              <th>Remisión</th>
              <th>Fecha</th>
              <th>Cliente</th>
              <th>Fecha de servicio</th>
              <th>Técnico</th>
              <th>Estado</th>
            </tr>

            {% for a in info %}
            <tr>
                <td><a href="/remission/{{a.remission}}/">{{a.remission}}</a></td>
                <td>{{a.date}}</td>
                <td><a href="/customer/{{a.customer.CCNIT}}/">{{a.customer.name}}</a></td>
                <td>{{a.dateService}}</td>
                <td><a href="/technician/{{a.technician.id_person}}/">{{a.technician.name}}</a></td>
                <td>{{a.stateRemission}}</td>
            </tr>
            {% endfor %}
            
          </table>
{% endif %}
{% endblock %}

main/templates/main/remission_detail.html
{% extends 'main/base.html' %}
{% block content %}

<h2>Detalle de remisión</h2>
{% if remission %}
    <div>
        <table>
            <tr>
                <th>Número de remisión: </th>
                <td>{{ remission.remission }}</td>
            </tr>
            <tr>
                <th>Fecha de remisión</th>
                <td>{{ remission.date }}</td>
            </tr>
            <tr>
            <tr>
                <th>Nombre de cliente:</th>
                <td>{{remission.customer}}</td>
            </tr>
            <tr>
                <th>Fecha de servicio</th>
                <td>{{remission.dateService}}</td>
            </tr>
            <tr>
                    <th>Técnico asignado</th>
                    <td>{{remission.technician}}</td>
            </tr>
            <tr>
                    <th>Observación</th>
                    <td>{{remission.Observation}}</td>
            </tr>
            <tr>
                    <th>Estado de remision</th>
                    <td>{{remission.stateRemission}}</td>
            </tr>
        </table>     
    </div>
    <h2>Servicios contratados</h2>
    {% for b in services %}
    <p>{{b.ID_service}}</p>
    <p>{{b.service}}</p>
    <input type="text" value="{{b.value}}"> 
    {% endfor %}
{% endif %}

{% endblock %}

main/templates/main/servi_detail.html
{% extends 'main/base.html' %}
{% block content %}

<h2>Detalle de servicio</h2>
{% if remission %}
    <div>
        <table>
                <form action="/SaveServi" method="get" id="saveForm">
                <td><input type="text" name="IDD" style="display: none;" value="{{remission.IDD}}"></td>           
            <tr>
                <th>ID</th>
                <td><input type="text" name="ID_service"  value="{{ remission.ID_service }}"></td>
            </tr>
            <tr>
            <tr>
                <th>Servicio</th>
                <td><input type="text" name="service"  value="{{remission.service}}"></td>
            </tr>
            <tr>
                <th>Costo</th>
                <td><input type="text" name="value"  value="{{remission.value}}"><br>
                <button type="submit">Guardar</button> </td>
            </tr>
        </table>     
    </div>
{% endif %}
{% endblock %}

main/templates/main/technicianList.html
{% extends 'main/base.html' %}
{% block content %}

<h2>Lista de técnicos</h2>

<div>
    <form action="/customerList" method="get" id="searchform">
        <input name="q" type="text" placeholder="Buscar aquí sus técnicos" value="{{query}}" required>
        <button type="submit">Buscar</button>
    </form>
</div>
{% if info %}
    <table>
            <tr>
              <th>CC o NIT</th>
              <th>Nombre</th>
              <th>Télefono</th>
              <th>Direeción</th>
            </tr>
            {% for a in info %}
            <tr>
                <td>{{a.id_person}}</td>
                <td>{{a.name}}</td>
                <td>{{a.phone}}</td>
                <td>{{a.address}}</td>
                <td><a href="/technician/{{a.id_person}}">Editar</a></td>
                <td><a id="{{a.IDD}}"  onclick="sure(this.id)" name="3" href="/">Eliminar</a></td>
            </tr>
            {% endfor %}
    </table>
{% endif %}
{% endblock %}

IDD = models.AutoField(primary_key=True)
id_person = models.CharField(max_length=200,unique=True)
name = models.CharField(max_length=200)
phone = models.CharField(max_length=200)
address =  models.CharField(max_length=200,default=' ')

main/templates/main/technician_detail.html
{% extends 'main/base.html' %}
{% block content %}

<h2>Detalle de ténico</h2>
{% if technician %}
    <div>
        <table>
                <form action="/SaveTecnician" method="get" id="saveForm">
                <td><input type="text" name="IDD" style="display: none;" value="{{technician.IDD}}"></td>           
            <tr>
                <th>Indentificación: </th>
                <td><input type="text" name="id_person"  value="{{ technician.id_person }}"></td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td><input type="text" name="name"  value="{{ technician.name }}"></td>
            </tr>
            <tr>
            <tr>
                <th>Télefono</th>
                <td><input type="text" name="phone"  value="{{technician.phone}}"></td>
            </tr>
            <tr>
                <th>Dirección</th>
                <td><input type="text" name="address"  value="{{technician.address}}"><br>
                <button type="submit">Guardar</button> </td>
            </tr>
        </table>     
    </div>
{% endif %}
{% endblock %}

main/templates/main/techniciansHistory.html
{% extends 'main/base.html' %}
{% block content %}

    <h2>Historial de técnicos</h2>

{% endblock %}